import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8080/');
  await page.getByRole('link', { name: ' Find owners' }).click();
  await page.getByRole('button', { name: 'Find Owner' }).click();
  await page.getByRole('link', { name: 'Betty Davis' }).click();
  await page.getByRole('link', { name: ' Find owners' }).click();
  await page.getByRole('link', { name: 'Add Owner' }).click();
  await page.locator('#firstName').click();
  await page.locator('#firstName').fill('Peter');
  await page.locator('#firstName').press('Tab');
  await page.locator('#lastName').fill('Jackson');
  await page.locator('#lastName').press('Tab');
  await page.locator('#address').fill('New Yorj');
  await page.locator('#address').press('Tab');
  await page.locator('div').filter({ hasText: 'Address' }).nth(3).click();
  await page.locator('#address').click();
  await page.locator('#address').fill('New York');
  await page.locator('#city').click();
  await page.locator('div').filter({ hasText: 'Address' }).nth(3).dblclick();
  await page.locator('#address').click({
    clickCount: 3
  });
  await page.locator('#address').press('Meta+c');
  await page.locator('#city').click();
  await page.locator('#city').fill('New York');
  await page.locator('div').filter({ hasText: 'Add Owner' }).nth(3).click();
  await page.locator('#telephone').click();
  await page.locator('#telephone').fill('+672541231');
  await page.getByRole('button', { name: 'Add Owner' }).click();
  await page.getByRole('link', { name: 'Add New Pet' }).click();
  await page.locator('#name').click();
  await page.locator('#name').fill('JoJo');
  await page.locator('#birthDate').fill('1999-10-15');
  await page.getByRole('button', { name: 'Add Pet' }).click();
  await page.getByRole('link', { name: ' Veterinarians' }).click();
  await page.getByRole('link', { name: ' Find owners' }).click();
  await page.getByRole('button', { name: 'Find Owner' }).click();
  await page.getByRole('link', { name: 'Peter Jackson' }).click();
  await page.getByRole('link', { name: 'Add Visit' }).click();
  await page.getByRole('link', { name: ' Find owners' }).click();
  await page.locator('#lastName').click();
  await page.locator('#lastName').fill('Jackson');
  await page.locator('#lastName').press('Enter');
  await page.getByRole('link', { name: 'Edit Pet' }).click();
  await page.getByRole('button', { name: 'Update Pet' }).click();
  await page.getByRole('link', { name: ' Find owners' }).click();
  await page.getByRole('link', { name: ' Find owners' }).click();
  await page.locator('#lastName').click();
  await page.locator('#lastName').fill('Jason');
  await page.locator('#lastName').press('Enter');
  await page.locator('#lastName').dblclick();
  await page.locator('#lastName').fill('');
  await page.getByRole('button', { name: 'Find Owner' }).click();
  await page.getByRole('link', { name: 'Eduardo Rodriquez' }).click();
  await page.getByRole('link', { name: 'Add Visit' }).click();
  await page.getByRole('link', { name: ' Veterinarians' }).click();
});